### ISSUE TITLE
Not an issue =P is it some kind of crawler?

### ISSUE THREAD

**Issue by onluiz** [FernandaBernardo/find-images-js#1]
Is it some kind of crawler?

**Comment by FernandaBernardo** [comment]
Yeap :)

**Comment by onluiz** [comment]
Cool =) Is it possible for me to contribute with something in this repository? Or is it to early for it? =P

**Comment by FernandaBernardo** [comment]
Of course! What are you thinking?

**Comment by onluiz** [comment]
Well, as I'm new with github and JS I would like to help creating tests and writing documentation. And of course, a can contribute with anything you ask me to.

What you think?

**Comment by FernandaBernardo** [comment]
Cool :) It would be nice to write the documentation and create tests. I like the ideia. About new things... Still have to make a custom input with a food list. Now, only works with `rice`.

**Comment by onluiz** [comment]
#2 =)
